name = "ModelAutoGrad"
uuid = "bb5ee08d-2263-4c56-8f83-dffd1335715f"
authors = ["Dongdong Kong <kongdd@users.noreply.github.com>"]
version = "0.1.0"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
ComponentArrays = "0.15.29"
Enzyme = "0.13.86"
LinearAlgebra = "1.11.0"
julia = "1.11.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
